"""add user_id to bookmark

Revision ID: 11b6009e2007
Revises: 7433c1c72223
Create Date: 2026-08-05 12:58:55.049280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '11b6009e2007'
down_revision: Union[str, Sequence[str], None] = '7433c1c72223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookmark', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE bookmark SET user_id = 2 WHERE user_id IS NULL")
    op.alter_column('bookmark', 'user_id', nullable=False)
    op.create_index(op.f('ix_bookmark_user_id'), 'bookmark', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bookmark', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmark', type_='foreignkey')
    op.drop_index(op.f('ix_bookmark_user_id'), table_name='bookmark')
    op.drop_column('bookmark', 'user_id')
    # ### end Alembic commands ###
