"""empty message

Revision ID: 58efe60bfdb5
Revises: 11b6009e2007
Create Date: 2026-08-05 22:50:15.477480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58efe60bfdb5'
down_revision: Union[str, Sequence[str], None] = '11b6009e2007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE tag SET user_id = 2 WHERE user_id IS NULL")
    op.alter_column('tag', 'user_id', nullable=False)
    op.create_index(op.f('ix_tag_user_id'), 'tag', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'tag', ['user_id', 'tag'])
    op.create_foreign_key(None, 'tag', 'user', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_constraint(None, 'tag', type_='unique')
    op.drop_index(op.f('ix_tag_user_id'), table_name='tag')
    op.drop_column('tag', 'user_id')
    # ### end Alembic commands ###
