"""add unique constraint on bookmark user_id and url

Revision ID: a2ed3fe00b22
Revises: 58efe60bfdb5
Create Date: 2026-08-05 23:07:13.071812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a2ed3fe00b22'
down_revision: Union[str, Sequence[str], None] = '58efe60bfdb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookmark', ['user_id', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmark', type_='unique')
    # ### end Alembic commands ###
